FROM golang:1.25.3 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags='-s -w' -o /out/ipfsniffer-server ./cmd/ipfsniffer-server

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /out/ipfsniffer-server /ipfsniffer-server
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/ipfsniffer-server"]
