// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.14.0
// source: extract.proto

package ipfsnifferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V     int32               `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Id    string              `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ts    string              `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Trace *TraceContext       `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Data  *ExtractRequestData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractRequest) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *ExtractRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtractRequest) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *ExtractRequest) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *ExtractRequest) GetData() *ExtractRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExtractRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCid    string           `protobuf:"bytes,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Path       string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mime       string           `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	SizeBytes  int64            `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentRef *ContentRef      `protobuf:"bytes,5,opt,name=content_ref,json=contentRef,proto3" json:"content_ref,omitempty"`
	Extractor  *ExtractorConfig `protobuf:"bytes,6,opt,name=extractor,proto3" json:"extractor,omitempty"`
}

func (x *ExtractRequestData) Reset() {
	*x = ExtractRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequestData) ProtoMessage() {}

func (x *ExtractRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequestData.ProtoReflect.Descriptor instead.
func (*ExtractRequestData) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractRequestData) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *ExtractRequestData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExtractRequestData) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ExtractRequestData) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ExtractRequestData) GetContentRef() *ContentRef {
	if x != nil {
		return x.ContentRef
	}
	return nil
}

func (x *ExtractRequestData) GetExtractor() *ExtractorConfig {
	if x != nil {
		return x.Extractor
	}
	return nil
}

type ContentRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode         string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	InlineBase64 string `protobuf:"bytes,2,opt,name=inline_base64,json=inlineBase64,proto3" json:"inline_base64,omitempty"`
}

func (x *ContentRef) Reset() {
	*x = ContentRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRef) ProtoMessage() {}

func (x *ContentRef) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRef.ProtoReflect.Descriptor instead.
func (*ContentRef) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{2}
}

func (x *ContentRef) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ContentRef) GetInlineBase64() string {
	if x != nil {
		return x.InlineBase64
	}
	return ""
}

type ExtractorConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preferred    string `protobuf:"bytes,1,opt,name=preferred,proto3" json:"preferred,omitempty"`
	TimeoutMs    int64  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxTextBytes int64  `protobuf:"varint,3,opt,name=max_text_bytes,json=maxTextBytes,proto3" json:"max_text_bytes,omitempty"`
}

func (x *ExtractorConfig) Reset() {
	*x = ExtractorConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractorConfig) ProtoMessage() {}

func (x *ExtractorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_extract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractorConfig.ProtoReflect.Descriptor instead.
func (*ExtractorConfig) Descriptor() ([]byte, []int) {
	return file_extract_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractorConfig) GetPreferred() string {
	if x != nil {
		return x.Preferred
	}
	return ""
}

func (x *ExtractorConfig) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExtractorConfig) GetMaxTextBytes() int64 {
	if x != nil {
		return x.MaxTextBytes
	}
	return 0
}

var File_extract_proto protoreflect.FileDescriptor

var file_extract_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x0e,
	0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8,
	0x01, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x73, 0x12,
	0x31, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf0, 0x01, 0x0a, 0x12, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65,
	0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69,
	0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x66, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x12, 0x3c,
	0x0a, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x09, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x36, 0x34, 0x22, 0x74, 0x0a, 0x0f, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x72, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x4d, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x61, 0x78,
	0x54, 0x65, 0x78, 0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x2f,
	0x49, 0x50, 0x46, 0x53, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extract_proto_rawDescOnce sync.Once
	file_extract_proto_rawDescData = file_extract_proto_rawDesc
)

func file_extract_proto_rawDescGZIP() []byte {
	file_extract_proto_rawDescOnce.Do(func() {
		file_extract_proto_rawDescData = protoimpl.X.CompressGZIP(file_extract_proto_rawDescData)
	})
	return file_extract_proto_rawDescData
}

var file_extract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_extract_proto_goTypes = []any{
	(*ExtractRequest)(nil),     // 0: ipfsniffer.v1.ExtractRequest
	(*ExtractRequestData)(nil), // 1: ipfsniffer.v1.ExtractRequestData
	(*ContentRef)(nil),         // 2: ipfsniffer.v1.ContentRef
	(*ExtractorConfig)(nil),    // 3: ipfsniffer.v1.ExtractorConfig
	(*TraceContext)(nil),       // 4: ipfsniffer.v1.TraceContext
}
var file_extract_proto_depIdxs = []int32{
	4, // 0: ipfsniffer.v1.ExtractRequest.trace:type_name -> ipfsniffer.v1.TraceContext
	1, // 1: ipfsniffer.v1.ExtractRequest.data:type_name -> ipfsniffer.v1.ExtractRequestData
	2, // 2: ipfsniffer.v1.ExtractRequestData.content_ref:type_name -> ipfsniffer.v1.ContentRef
	3, // 3: ipfsniffer.v1.ExtractRequestData.extractor:type_name -> ipfsniffer.v1.ExtractorConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_extract_proto_init() }
func file_extract_proto_init() {
	if File_extract_proto != nil {
		return
	}
	file_envelope_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_extract_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ExtractRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extract_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExtractRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extract_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ContentRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extract_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExtractorConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extract_proto_goTypes,
		DependencyIndexes: file_extract_proto_depIdxs,
		MessageInfos:      file_extract_proto_msgTypes,
	}.Build()
	File_extract_proto = out.File
	file_extract_proto_rawDesc = nil
	file_extract_proto_goTypes = nil
	file_extract_proto_depIdxs = nil
}
