// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.14.0
// source: fetch.proto

package ipfsnifferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V     int32             `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Id    string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ts    string            `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Trace *TraceContext     `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Data  *FetchRequestData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *FetchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FetchRequest) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *FetchRequest) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *FetchRequest) GetData() *FetchRequestData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FetchRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCid    string        `protobuf:"bytes,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Path       string        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Limits     *FetchLimits  `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
	Policy     *FetchPolicy  `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	Content    *FetchContent `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ObservedAt string        `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
}

func (x *FetchRequestData) Reset() {
	*x = FetchRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequestData) ProtoMessage() {}

func (x *FetchRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequestData.ProtoReflect.Descriptor instead.
func (*FetchRequestData) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *FetchRequestData) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FetchRequestData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FetchRequestData) GetLimits() *FetchLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *FetchRequestData) GetPolicy() *FetchPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *FetchRequestData) GetContent() *FetchContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchRequestData) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

type FetchLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTotalBytes int64 `protobuf:"varint,1,opt,name=max_total_bytes,json=maxTotalBytes,proto3" json:"max_total_bytes,omitempty"`
	MaxFileBytes  int64 `protobuf:"varint,2,opt,name=max_file_bytes,json=maxFileBytes,proto3" json:"max_file_bytes,omitempty"`
	MaxDagNodes   int64 `protobuf:"varint,3,opt,name=max_dag_nodes,json=maxDagNodes,proto3" json:"max_dag_nodes,omitempty"`
	MaxDepth      int64 `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	TimeoutMs     int64 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
}

func (x *FetchLimits) Reset() {
	*x = FetchLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLimits) ProtoMessage() {}

func (x *FetchLimits) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLimits.ProtoReflect.Descriptor instead.
func (*FetchLimits) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{2}
}

func (x *FetchLimits) GetMaxTotalBytes() int64 {
	if x != nil {
		return x.MaxTotalBytes
	}
	return 0
}

func (x *FetchLimits) GetMaxFileBytes() int64 {
	if x != nil {
		return x.MaxFileBytes
	}
	return 0
}

func (x *FetchLimits) GetMaxDagNodes() int64 {
	if x != nil {
		return x.MaxDagNodes
	}
	return 0
}

func (x *FetchLimits) GetMaxDepth() int64 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *FetchLimits) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type FetchPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkipExt        []string `protobuf:"bytes,1,rep,name=skip_ext,json=skipExt,proto3" json:"skip_ext,omitempty"`
	SkipMimePrefix []string `protobuf:"bytes,2,rep,name=skip_mime_prefix,json=skipMimePrefix,proto3" json:"skip_mime_prefix,omitempty"`
}

func (x *FetchPolicy) Reset() {
	*x = FetchPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPolicy) ProtoMessage() {}

func (x *FetchPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPolicy.ProtoReflect.Descriptor instead.
func (*FetchPolicy) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{3}
}

func (x *FetchPolicy) GetSkipExt() []string {
	if x != nil {
		return x.SkipExt
	}
	return nil
}

func (x *FetchPolicy) GetSkipMimePrefix() []string {
	if x != nil {
		return x.SkipMimePrefix
	}
	return nil
}

type FetchContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InlineMaxBytes int64 `protobuf:"varint,1,opt,name=inline_max_bytes,json=inlineMaxBytes,proto3" json:"inline_max_bytes,omitempty"`
}

func (x *FetchContent) Reset() {
	*x = FetchContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchContent) ProtoMessage() {}

func (x *FetchContent) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchContent.ProtoReflect.Descriptor instead.
func (*FetchContent) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{4}
}

func (x *FetchContent) GetInlineMaxBytes() int64 {
	if x != nil {
		return x.InlineMaxBytes
	}
	return 0
}

type FetchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V     int32            `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	Id    string           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ts    string           `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Trace *TraceContext    `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	Data  *FetchResultData `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FetchResult) Reset() {
	*x = FetchResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResult) ProtoMessage() {}

func (x *FetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResult.ProtoReflect.Descriptor instead.
func (*FetchResult) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResult) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *FetchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FetchResult) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *FetchResult) GetTrace() *TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *FetchResult) GetData() *FetchResultData {
	if x != nil {
		return x.Data
	}
	return nil
}

type FetchResultData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootCid    string              `protobuf:"bytes,1,opt,name=root_cid,json=rootCid,proto3" json:"root_cid,omitempty"`
	Path       string              `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NodeType   string              `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	SizeBytes  int64               `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Mime       string              `protobuf:"bytes,5,opt,name=mime,proto3" json:"mime,omitempty"`
	Ext        string              `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`
	Content    *FetchContentResult `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Directory  *FetchDirectory     `protobuf:"bytes,8,opt,name=directory,proto3" json:"directory,omitempty"`
	Status     string              `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	SkipReason string              `protobuf:"bytes,10,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`
	Error      string              `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	FetchedAt  string              `protobuf:"bytes,12,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	ObservedAt string              `protobuf:"bytes,13,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
}

func (x *FetchResultData) Reset() {
	*x = FetchResultData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchResultData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResultData) ProtoMessage() {}

func (x *FetchResultData) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResultData.ProtoReflect.Descriptor instead.
func (*FetchResultData) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{6}
}

func (x *FetchResultData) GetRootCid() string {
	if x != nil {
		return x.RootCid
	}
	return ""
}

func (x *FetchResultData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FetchResultData) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *FetchResultData) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FetchResultData) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FetchResultData) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FetchResultData) GetContent() *FetchContentResult {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FetchResultData) GetDirectory() *FetchDirectory {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *FetchResultData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FetchResultData) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

func (x *FetchResultData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchResultData) GetFetchedAt() string {
	if x != nil {
		return x.FetchedAt
	}
	return ""
}

func (x *FetchResultData) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

type FetchContentResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode         string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	InlineBase64 string `protobuf:"bytes,2,opt,name=inline_base64,json=inlineBase64,proto3" json:"inline_base64,omitempty"`
}

func (x *FetchContentResult) Reset() {
	*x = FetchContentResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchContentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchContentResult) ProtoMessage() {}

func (x *FetchContentResult) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchContentResult.ProtoReflect.Descriptor instead.
func (*FetchContentResult) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{7}
}

func (x *FetchContentResult) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FetchContentResult) GetInlineBase64() string {
	if x != nil {
		return x.InlineBase64
	}
	return ""
}

type FetchDirectory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries   []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Truncated bool     `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
}

func (x *FetchDirectory) Reset() {
	*x = FetchDirectory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDirectory) ProtoMessage() {}

func (x *FetchDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDirectory.ProtoReflect.Descriptor instead.
func (*FetchDirectory) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{8}
}

func (x *FetchDirectory) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FetchDirectory) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_fetch_proto protoreflect.FileDescriptor

var file_fetch_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x65, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x69,
	0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x0e, 0x65, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a,
	0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x05, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x70, 0x66,
	0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x33,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69,
	0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x81, 0x02, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74,
	0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74,
	0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69,
	0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x73, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x70,
	0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12,
	0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x6d, 0x61, 0x78, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x61, 0x67,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x61,
	0x78, 0x44, 0x61, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78,
	0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61,
	0x78, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x4d, 0x73, 0x22, 0x52, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x45, 0x78, 0x74, 0x12,
	0x28, 0x0a, 0x10, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6b, 0x69, 0x70, 0x4d,
	0x69, 0x6d, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x38, 0x0a, 0x0c, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x61, 0x78, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x76, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x73, 0x12, 0x31, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x05, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xab, 0x03, 0x0a, 0x0f, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x6f, 0x74, 0x43, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65,
	0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69,
	0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x3b, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x70, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x65, 0x74, 0x63,
	0x68, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4d, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36,
	0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x48, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74, 0x72, 0x75, 0x6e, 0x63, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f,
	0x72, 0x69, 0x63, 0x61, 0x6c, 0x2f, 0x49, 0x50, 0x46, 0x53, 0x6e, 0x69, 0x66, 0x66, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x69, 0x70, 0x66, 0x73, 0x6e, 0x69, 0x66, 0x66, 0x65,
	0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fetch_proto_rawDescOnce sync.Once
	file_fetch_proto_rawDescData = file_fetch_proto_rawDesc
)

func file_fetch_proto_rawDescGZIP() []byte {
	file_fetch_proto_rawDescOnce.Do(func() {
		file_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(file_fetch_proto_rawDescData)
	})
	return file_fetch_proto_rawDescData
}

var file_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_fetch_proto_goTypes = []any{
	(*FetchRequest)(nil),       // 0: ipfsniffer.v1.FetchRequest
	(*FetchRequestData)(nil),   // 1: ipfsniffer.v1.FetchRequestData
	(*FetchLimits)(nil),        // 2: ipfsniffer.v1.FetchLimits
	(*FetchPolicy)(nil),        // 3: ipfsniffer.v1.FetchPolicy
	(*FetchContent)(nil),       // 4: ipfsniffer.v1.FetchContent
	(*FetchResult)(nil),        // 5: ipfsniffer.v1.FetchResult
	(*FetchResultData)(nil),    // 6: ipfsniffer.v1.FetchResultData
	(*FetchContentResult)(nil), // 7: ipfsniffer.v1.FetchContentResult
	(*FetchDirectory)(nil),     // 8: ipfsniffer.v1.FetchDirectory
	(*TraceContext)(nil),       // 9: ipfsniffer.v1.TraceContext
}
var file_fetch_proto_depIdxs = []int32{
	9, // 0: ipfsniffer.v1.FetchRequest.trace:type_name -> ipfsniffer.v1.TraceContext
	1, // 1: ipfsniffer.v1.FetchRequest.data:type_name -> ipfsniffer.v1.FetchRequestData
	2, // 2: ipfsniffer.v1.FetchRequestData.limits:type_name -> ipfsniffer.v1.FetchLimits
	3, // 3: ipfsniffer.v1.FetchRequestData.policy:type_name -> ipfsniffer.v1.FetchPolicy
	4, // 4: ipfsniffer.v1.FetchRequestData.content:type_name -> ipfsniffer.v1.FetchContent
	9, // 5: ipfsniffer.v1.FetchResult.trace:type_name -> ipfsniffer.v1.TraceContext
	6, // 6: ipfsniffer.v1.FetchResult.data:type_name -> ipfsniffer.v1.FetchResultData
	7, // 7: ipfsniffer.v1.FetchResultData.content:type_name -> ipfsniffer.v1.FetchContentResult
	8, // 8: ipfsniffer.v1.FetchResultData.directory:type_name -> ipfsniffer.v1.FetchDirectory
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_fetch_proto_init() }
func file_fetch_proto_init() {
	if File_fetch_proto != nil {
		return
	}
	file_envelope_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fetch_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FetchRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FetchLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FetchPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FetchContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FetchResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FetchResultData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FetchContentResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fetch_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FetchDirectory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fetch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fetch_proto_goTypes,
		DependencyIndexes: file_fetch_proto_depIdxs,
		MessageInfos:      file_fetch_proto_msgTypes,
	}.Build()
	File_fetch_proto = out.File
	file_fetch_proto_rawDesc = nil
	file_fetch_proto_goTypes = nil
	file_fetch_proto_depIdxs = nil
}
